user.exception=user_failure

character.exception=character_failure